#!/bin/bash
# HSC-JIT v3.5 QUICK COMMAND REFERENCE
# Copy-paste commands for deployment and operations

echo "═══════════════════════════════════════════════════════════"
echo "  HSC-JIT v3.5 - QUICK COMMAND REFERENCE"
echo "═══════════════════════════════════════════════════════════"
echo ""

# Color codes
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}📦 INSTALLATION (Run Once)${NC}"
echo "─────────────────────────────────────────────────────────"
echo ""
echo "1️⃣  Install Playwright & dependencies:"
echo "   pip install playwright httpx"
echo ""
echo "2️⃣  Install Chromium browser:"
echo "   playwright install chromium"
echo ""
echo "3️⃣  Deploy production cron automation:"
echo "   bash /workspaces/hsc-jit-v3/backend/scripts/install_production_automation.sh"
echo ""
echo ""

echo -e "${BLUE}🧪 TESTING & VALIDATION${NC}"
echo "─────────────────────────────────────────────────────────"
echo ""
echo "1️⃣  Test enhanced brand scraper:"
echo "   python /workspaces/hsc-jit-v3/backend/scripts/playwright_brand_scraper.py"
echo ""
echo "2️⃣  Test health monitoring:"
echo "   python /workspaces/hsc-jit-v3/backend/scripts/production_monitor.py"
echo ""
echo "3️⃣  Test with auto-recovery:"
echo "   python /workspaces/hsc-jit-v3/backend/scripts/production_monitor.py --auto-recover"
echo ""
echo "4️⃣  Generate daily report:"
echo "   python /workspaces/hsc-jit-v3/backend/scripts/daily_report_generator.py"
echo ""
echo ""

echo -e "${BLUE}📊 MONITORING & METRICS${NC}"
echo "─────────────────────────────────────────────────────────"
echo ""
echo "View current coverage metrics:"
echo "   curl http://localhost:8000/api/dual-source-intelligence | jq '.global_stats'"
echo ""
echo "Watch full sync in progress:"
echo "   tail -f /workspaces/hsc-jit-v3/backend/logs/automation/full_sync.log"
echo ""
echo "Monitor all automation logs:"
echo "   tail -f /workspaces/hsc-jit-v3/backend/logs/automation/*.log"
echo ""
echo "View health report:"
echo "   cat /workspaces/hsc-jit-v3/backend/logs/health_report.json | jq"
echo ""
echo "View daily reports:"
echo "   ls -lh /workspaces/hsc-jit-v3/backend/logs/reports/"
echo "   cat /workspaces/hsc-jit-v3/backend/logs/reports/report_*.json | jq '.summary'"
echo ""
echo ""

echo -e "${BLUE}🔧 MANUAL SYNC OPERATIONS${NC}"
echo "─────────────────────────────────────────────────────────"
echo ""
echo "Full ecosystem sync (all brands):"
echo "   cd /workspaces/hsc-jit-v3/backend"
echo "   python scripts/ecosystem_orchestrator.py --mode=full"
echo ""
echo "Quick pricing update (Halilit only):"
echo "   python scripts/ecosystem_orchestrator.py --mode=quick"
echo ""
echo "Sync specific brand:"
echo "   python scripts/ecosystem_orchestrator.py --brand=roland"
echo "   python scripts/ecosystem_orchestrator.py --brand=pearl"
echo "   python scripts/ecosystem_orchestrator.py --brand=mackie"
echo ""
echo "Sync multiple brands:"
echo "   python scripts/ecosystem_orchestrator.py --brands roland pearl mackie"
echo ""
echo ""

echo -e "${BLUE}📅 CRON JOB MANAGEMENT${NC}"
echo "─────────────────────────────────────────────────────────"
echo ""
echo "View all installed cron jobs:"
echo "   crontab -l | grep -A50 'ECOSYSTEM INTELLIGENCE'"
echo ""
echo "View just the installed job count:"
echo "   crontab -l | grep -c ECOSYSTEM"
echo ""
echo "Edit cron jobs (advanced):"
echo "   crontab -e"
echo ""
echo "Remove all ecosystem jobs:"
echo "   crontab -l | grep -v ECOSYSTEM | crontab -"
echo ""
echo "Remove all jobs (caution!):"
echo "   crontab -r"
echo ""
echo ""

echo -e "${BLUE}🔍 TROUBLESHOOTING${NC}"
echo "─────────────────────────────────────────────────────────"
echo ""
echo "Check if API is running:"
echo "   curl -I http://localhost:8000/health"
echo ""
echo "Check for scraper errors:"
echo "   grep -i error /workspaces/hsc-jit-v3/backend/logs/automation/*.log | tail -20"
echo ""
echo "Check Playwright installation:"
echo "   python -c \"from playwright.async_api import async_playwright; print('✅ OK')\""
echo ""
echo "View last 20 errors in sync:"
echo "   tail -100 /workspaces/hsc-jit-v3/backend/logs/automation/full_sync.log | grep -i error"
echo ""
echo "Check disk space:"
echo "   df -h /workspaces/hsc-jit-v3"
echo ""
echo "Check for duplicate entries in crontab:"
echo "   crontab -l | grep ECOSYSTEM | sort | uniq -d"
echo ""
echo ""

echo -e "${BLUE}📋 DATA INSPECTION${NC}"
echo "─────────────────────────────────────────────────────────"
echo ""
echo "Check Roland scraper results:"
echo "   cat /workspaces/hsc-jit-v3/backend/data/catalogs_brand/roland_catalog.json | jq '.total_products'"
echo ""
echo "Check unified catalog size:"
echo "   ls -lh /workspaces/hsc-jit-v3/backend/data/catalogs_unified/"
echo ""
echo "View top-level stats:"
echo "   python << 'EOF'"
echo "import json"
echo "with open('/workspaces/hsc-jit-v3/backend/data/catalogs_unified/nord_catalog.json') as f:"
echo "    data = json.load(f)"
echo "    print(f\"Total: {len(data['products'])}\")"
echo "    primary = len([p for p in data['products'] if p.get('source') == 'PRIMARY'])"
echo "    print(f\"PRIMARY: {primary}\")"
echo "EOF"
echo ""
echo ""

echo -e "${BLUE}🚀 DEPLOYMENT CHECKLIST${NC}"
echo "─────────────────────────────────────────────────────────"
echo ""
echo "[ ] 1. Install Playwright: pip install playwright httpx"
echo "[ ] 2. Install browser: playwright install chromium"
echo "[ ] 3. Test scraper: python scripts/playwright_brand_scraper.py"
echo "[ ] 4. Deploy cron: bash scripts/install_production_automation.sh"
echo "[ ] 5. Verify health: python scripts/production_monitor.py"
echo "[ ] 6. Check API: curl http://localhost:8000/api/dual-source-intelligence"
echo "[ ] 7. View metrics: jq '.global_stats' from API response"
echo "[ ] 8. Monitor logs: tail -f logs/automation/*.log"
echo ""
echo ""

echo -e "${GREEN}✅ READY TO DEPLOY!${NC}"
echo ""
echo "Next step: bash /workspaces/hsc-jit-v3/backend/scripts/install_production_automation.sh"
echo ""
echo "═══════════════════════════════════════════════════════════"
