/**
 * Taxonomy Loader - Loads brand taxonomy from static JSON
 *
 * This module loads the pre-built taxonomy.json file that contains
 * all official brand categories. The Navigator and TierBar use this
 * for category navigation and filtering.
 *
 * Architecture: Static JSON loaded once, cached in memory.
 * Source: Generated by backend/models/taxonomy_registry.py
 */

export interface TaxonomyCategory {
  id: string;
  label: string;
  parent_id: string | null;
  children: string[];
  icon?: string;
  description?: string;
}

export interface BrandTaxonomy {
  brand_id: string;
  brand_name: string;
  base_url: string;
  last_verified: string;
  categories: TaxonomyCategory[];
  root_categories: TaxonomyCategory[];
}

export interface TaxonomyRegistry {
  version: string;
  generated_at: string;
  brands: Record<string, BrandTaxonomy>;
}

// Cache for loaded taxonomy
let _taxonomyCache: TaxonomyRegistry | null = null;
let _loadingPromise: Promise<TaxonomyRegistry> | null = null;

/**
 * Load the taxonomy registry from static JSON
 * Only loads once, returns cached version on subsequent calls
 */
export async function loadTaxonomyRegistry(): Promise<TaxonomyRegistry> {
  if (_taxonomyCache) {
    return _taxonomyCache;
  }

  if (_loadingPromise) {
    return _loadingPromise;
  }

  _loadingPromise = fetch(`/data/taxonomy.json?v=${Date.now()}`)
    .then((response) => {
      if (!response.ok) {
        console.warn("Taxonomy not found, using fallback");
        return getFallbackTaxonomy();
      }
      return response.json() as Promise<TaxonomyRegistry>;
    })
    .then((data) => {
      _taxonomyCache = data;
      console.log(
        `📋 Taxonomy loaded: ${Object.keys(data.brands).length} brands`
      );
      return data;
    })
    .catch((error) => {
      console.error("Failed to load taxonomy:", error);
      _taxonomyCache = getFallbackTaxonomy();
      return _taxonomyCache;
    });

  return _loadingPromise;
}

/**
 * Get taxonomy for a specific brand (synchronous, from cache)
 * Returns null if taxonomy not loaded yet
 */
export function getBrandTaxonomySync(brandId: string): BrandTaxonomy | null {
  if (!_taxonomyCache) {
    return null;
  }
  return _taxonomyCache.brands[brandId.toLowerCase()] || null;
}

/**
 * Get root categories for a brand (async)
 */
export async function getBrandRootCategories(
  brandId: string
): Promise<TaxonomyCategory[]> {
  const registry = await loadTaxonomyRegistry();
  const brandTaxonomy = registry.brands[brandId.toLowerCase()];
  if (!brandTaxonomy) {
    return [];
  }
  return brandTaxonomy.root_categories || [];
}

/**
 * Get all categories for a brand (async)
 */
export async function getBrandCategories(
  brandId: string
): Promise<TaxonomyCategory[]> {
  const registry = await loadTaxonomyRegistry();
  const brandTaxonomy = registry.brands[brandId.toLowerCase()];
  if (!brandTaxonomy) {
    return [];
  }
  return brandTaxonomy.categories || [];
}

/**
 * Get category labels for tier bar filtering
 */
export async function getCategoryLabels(brandId: string): Promise<string[]> {
  const categories = await getBrandRootCategories(brandId);
  return categories.map((cat) => cat.label);
}

/**
 * Check if a category exists for a brand
 */
export function validateCategory(
  brandId: string,
  category: string
): boolean {
  const taxonomy = getBrandTaxonomySync(brandId);
  if (!taxonomy) return false;

  const catLower = category.toLowerCase();
  return taxonomy.categories.some(
    (cat) =>
      cat.id.toLowerCase() === catLower ||
      cat.label.toLowerCase() === catLower
  );
}

/**
 * Get all available brand IDs from taxonomy
 */
export async function getAvailableBrands(): Promise<string[]> {
  const registry = await loadTaxonomyRegistry();
  return Object.keys(registry.brands);
}

/**
 * Fallback taxonomy when JSON isn't loaded yet
 * This matches the hardcoded categories in brandTaxonomy.ts
 */
function getFallbackTaxonomy(): TaxonomyRegistry {
  return {
    version: "fallback",
    generated_at: new Date().toISOString(),
    brands: {
      roland: {
        brand_id: "roland",
        brand_name: "Roland",
        base_url: "https://www.roland.com/global",
        last_verified: "",
        categories: [],
        root_categories: [
          { id: "pianos", label: "Pianos", parent_id: null, children: [], icon: "🎹" },
          { id: "synthesizers", label: "Synthesizers", parent_id: null, children: [], icon: "🎛️" },
          { id: "keyboards", label: "Keyboards", parent_id: null, children: [], icon: "⌨️" },
          { id: "drums_percussion", label: "Drums & Percussion", parent_id: null, children: [], icon: "🥁" },
          { id: "amplifiers", label: "Amplifiers", parent_id: null, children: [], icon: "🔊" },
          { id: "accessories", label: "Accessories", parent_id: null, children: [], icon: "🔧" },
        ],
      },
      boss: {
        brand_id: "boss",
        brand_name: "BOSS",
        base_url: "https://www.boss.info/global",
        last_verified: "",
        categories: [],
        root_categories: [
          { id: "effects_pedals", label: "Effects Pedals", parent_id: null, children: [], icon: "🎸" },
          { id: "multi_effects", label: "Multi-Effects", parent_id: null, children: [], icon: "🎛️" },
          { id: "amplifiers", label: "Amplifiers", parent_id: null, children: [], icon: "🔊" },
          { id: "accessories", label: "Accessories", parent_id: null, children: [], icon: "🔧" },
        ],
      },
      nord: {
        brand_id: "nord",
        brand_name: "Nord",
        base_url: "https://www.nordkeyboards.com",
        last_verified: "",
        categories: [],
        root_categories: [
          { id: "stage", label: "Stage", parent_id: null, children: [], icon: "🎹" },
          { id: "piano", label: "Piano", parent_id: null, children: [], icon: "🎹" },
          { id: "electro", label: "Electro", parent_id: null, children: [], icon: "🎹" },
          { id: "lead", label: "Lead", parent_id: null, children: [], icon: "🎛️" },
        ],
      },
      moog: {
        brand_id: "moog",
        brand_name: "Moog",
        base_url: "https://www.moogmusic.com",
        last_verified: "",
        categories: [],
        root_categories: [
          { id: "synthesizers", label: "Synthesizers", parent_id: null, children: [], icon: "🎛️" },
          { id: "effects", label: "Effects", parent_id: null, children: [], icon: "🎸" },
          { id: "accessories", label: "Accessories", parent_id: null, children: [], icon: "🔧" },
        ],
      },
    },
  };
}

// Pre-load taxonomy on module import (non-blocking)
if (typeof window !== "undefined") {
  loadTaxonomyRegistry().catch(() => {
    // Silent fail, fallback will be used
  });
}
